import type { Metadata } from "next";
import { Inter, Bricolage_Grotesque } from "next/font/google";
import "./globals.css";
import ThemeProvider from "./ThemeProvider";
import ConditionalNavbar from "./components/ConditionalNavbar";
import ConditionalFooter from "./components/ConditionalFooter";
import { Toaster } from "react-hot-toast";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  display: "swap",
});

const bricolageGrotesque = Bricolage_Grotesque({
  variable: "--font-bricolage-grotesque",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Campus X",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${bricolageGrotesque.variable} antialiased`}
      >
        <ThemeProvider>
          <Toaster position="top-right" />
          <div className="w-full flex justify-center">
            <div className="w-full max-w-[1400px] flex flex-col min-h-screen">
              <ConditionalNavbar />
              <main className="flex-grow">
                {children}
              </main>
              <ConditionalFooter />
            </div>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
